version: '3.9'

services:
  weaviate:
    image: semitechnologies/weaviate:1.24.10
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: /var/lib/weaviate
      DEFAULT_VECTORIZER_MODULE: text2vec-openai
      ENABLE_MODULES: text2vec-openai
      OPENAI_APIKEY: ${OPENAI_APIKEY}
    ports:
      - '8080:8080'
    volumes:
      - weaviate_data:/var/lib/weaviate

  neo4j:
    image: neo4j:5-community
    environment:
      NEO4J_AUTH: neo4j/${NEO4J_PASSWORD}
    ports:
      - '7474:7474'
      - '7687:7687'
    volumes:
      - neo4j_data:/data

  redis:
    image: redis:7
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  app:
    build: .
    command: uvicorn src.api.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./:/app
    environment:
      - OPENAI_APIKEY=${OPENAI_APIKEY}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
    depends_on:
      - weaviate
      - neo4j
      - redis
    ports:
      - '8000:8000'

volumes:
  weaviate_data:
  neo4j_data:
  redis_data:
